from enum import Enum


class OpportunityType(Enum):
    FREELANCE = "FREELANCE"
    SERVICE = "SERVICE"
    PRODUCT = "PRODUCT"
    SAAS = "SAAS"
    GAME = "GAME"
    DIGITAL_ASSET = "DIGITAL_ASSET"
    RECURRING_REVENUE = "RECURRING_REVENUE"
    PARTNERSHIP = "PARTNERSHIP"
    INVESTMENT = "INVESTMENT"
    ACQUISITION = "ACQUISITION"
